### ISSUE TITLE
Optimization Profiles

### ISSUE THREAD

**Issue by BlissChapman** [jloloew/Etch-a-Sketch#1]
Look into the use of Xcode's optimization profiles:
https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/xcode_profile_guided_optimization/pgo-tasks/pgo-tasks.html

**Comment by jloloew** [comment]
No, at least for now. I want to minimize the differences between the iOS and Linux ports. (Plus, I've been running with -O0 to verify 100% code correctness recently.) Get the build working with Makefiles under Linux, then ask again.
